# Basic
title: 吴龙涛
subtitle: 知识仓库
description: keep it simple, stupid
# 头像里面的标题
avatarTitle: eust-w
# 头像里面的描述
avatarDesc: 云计算/物理/人工智障
url: "https://eust-w.cn"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
# comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726
    github: eust-w
    zhihu: 吴龙涛
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter:
    mail: eustancewu@gmail.com



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 工具, description: game, url: '/fun'}
    - {title: 学习, description: learn, url: '/learn'}
    - {title: 产品, description: product, url: '/product'}
    - {title: 友链, description: friends, url: '/friends'}

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


